package cn.ac.sitp.infrared.ai.model;

import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/**
 * Execution plan generated by TaskPlanningAgent.
 * Contains ordered steps for PlanExecutor to execute.
 */
public class ExecutionPlan {

    private String planId;
    private List<PlanStep> steps = new ArrayList<>();

    public ExecutionPlan() {
        this.planId = UUID.randomUUID().toString();
    }

    public ExecutionPlan addStep(PlanStep step) {
        step.setStep(steps.size() + 1);
        this.steps.add(step);
        return this;
    }

    public String getPlanId() { return planId; }
    public void setPlanId(String planId) { this.planId = planId; }
    public List<PlanStep> getSteps() { return steps; }
    public void setSteps(List<PlanStep> steps) { this.steps = steps; }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Plan[" + planId + "]:\n");
        for (PlanStep s : steps) {
            sb.append("  Step ").append(s.getStep())
              .append(": ").append(s.getAgent())
              .append(".").append(s.getTool())
              .append("(").append(s.getArgs()).append(")\n");
        }
        return sb.toString();
    }
}
