#infrared local db source
spring.datasource.infrareddb.url=jdbc:postgresql://localhost:5432/infrared_earth
spring.datasource.infrareddb.username=postgres
spring.datasource.infrareddb.password=123456
spring.datasource.infrareddb.driverClassName=org.postgresql.Driver
banner.charset=UTF-8
server.port=8080
server.tomcat.uri-encoding=UTF-8
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
server.servlet.context-path=/infrared
spring.messages.encoding=UTF-8
#session timeout: minutes
server.servlet.session.timeout=1800
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
#logs
logging.config=classpath:logback-spring.xml
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
#project config
app.login.maxfailurecount=5
app.login.lockminutes=5
app.login.expiredday=180
accessFile.resourceHandler=/files/**
accessFile.accessFilePath=/
